### ISSUE TITLE
Error on add_error when not inside an exception handler

### ISSUE THREAD

**Issue by boazin** [slash-testing/slash#277]
The test:
```
import slash

def test_empty():
    slash.add_error()
```

traceback:
```
Traceback (most recent call last):
  File "/Users/boazin/sentinal/QA/.env/lib/python2.7/site-packages/slash/core/result.py", line 97, in _add_error
    error = Error.capture_exception()
  File "/Users/boazin/sentinal/QA/.env/lib/python2.7/site-packages/slash/core/error.py", line 39, in capture_exception
    returned = exc_value.__slash_captured_error__ = cls(exc_info=exc_info)
AttributeError: 'NoneType' object has no attribute '__slash_captured_error__'
```

what I figured out:
in _add_error:
error is None - so we go to capture_exception - the thing is `sys.exc_info()` has no exception.

Not sure what was the intent to do in this case

**Comment by vmalloc** [comment]
I'm going to fix this to raise a RuntimeError. add_error() needs something to go by, either an error string or inside an exception...
