### ISSUE TITLE
[xunit-plugin] xunit start_session didn't run, and failed on the start of the first test

### ISSUE THREAD

**Issue by eplaut** [slash-testing/slash#309]
Hi, while running a slash test I got the error below:

```
slash run -vv test.py --with-xunit --xunit-filenam="test.xml" --truncate-console-lines no
[2015-05-31 15:18:15.176162] INFO: Generic: Test tests/windows/test_sanity.py failed
 on Windows_7_x86

0 tests collected...
1 tests collected...
1 tests collected   
2015-05-31 15:18:15 23497 slash.runner:run_tests:48 NOTICE> test.py:test_sanity
No handlers could be found for logger "gossip.hooks"

Traceback (most recent call last):
  File "/usr/local/bin/slash", line 9, in <module>
    load_entry_point('slash==0.15.0', 'console_scripts', 'slash')()
  File "/usr/local/lib/python2.7/dist-packages/slash/frontend/main.py", line 58, in main_entry_point
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/slash/frontend/main.py", line 41, in main
    return func(args.argv)
  File "/usr/local/lib/python2.7/dist-packages/slash/frontend/slash_run.py", line 38, in slash_run
    run_tests(collected)
  File "/usr/local/lib/python2.7/dist-packages/slash/runner.py", line 50, in run_tests
    with _get_run_context_stack(test, test_iterator, scope_manager) as should_run:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/slash/runner.py", line 105, in _get_run_context_stack
    stack.enter_context(_get_test_hooks_context())
  File "/usr/local/lib/python2.7/dist-packages/contextlib2.py", line 217, in enter_context
    result = _cm_type.__enter__(cm)
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/slash/runner.py", line 159, in _get_test_hooks_context
    hooks.test_start()  # pylint: disable=no-member
  File "/usr/local/lib/python2.7/dist-packages/gossip/hooks.py", line 57, in __call__
    return self.trigger(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gossip/hooks.py", line 129, in trigger
    break
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/gossip/exception_policy.py", line 18, in context
    self._handle_trigger_end(ctx)
  File "/usr/local/lib/python2.7/dist-packages/gossip/exception_policy.py", line 36, in _handle_trigger_end
    reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/gossip/hooks.py", line 134, in _call_registration
    registration(**kwargs)  # pylint: disable=star-args
  File "/usr/local/lib/python2.7/dist-packages/gossip/registration.py", line 43, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/slash/plugins/builtin/xunit.py", line 30, in test_start
    self._xunit_elements.append(E("testcase", {
AttributeError: 'Plugin' object has no attribute '_xunit_elements'
```

**Comment by vmalloc** [comment]
I'm guessing there was some other failure involved on session init?

**Comment by eplaut** [comment]
I'm sure you are right, but I can't point of any error.
since all the stack is inner for the slash framework, I assuming there some validation missing in the code.
additional information I can add that there is a backslash plugin that run, and failed, but return without exception.
