### ISSUE TITLE
[plugins] while any AssertionError cause fail, the hooks.add_failure run only on TestFailed error

### ISSUE THREAD

**Issue by eplaut** [slash-testing/slash#310]
Hi,

There is mismatching between the output slash gives and the plugins behaviour.
slash is failing for each AssertionError, the hooks.test_failure runs only for TestFailed error (```slash/runner.py:_get_test_hooks_context```)

```
$ cat test.py 
import slash

def test_error():
    assert False, "this is error"

def test_fail():
    slash.assert_true(False, "this is failure")
```

```
$ slash run test.py --with-xunit 
2 tests collected   
test.py FF  FAIL
================================================================================================== Session Summary ==================================================================================================
== #1: test.py:test_error ===========================================================================================================================================================================================
 - Additional Details:
    > Log: '/home/eli/sentinel-qa-results/6e7b0ae0-09cc-11e5-bd41-28d24459a522_0/6e7b0ae0-09cc-11e5-bd41-28d24459a522_0_1/debug.log.txt'
 - 1/1 F (2015-06-03 11:42:13 +03:00):   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 /home/eli/qa/test.py:4
 def test_error():
>    assert False, "this is error"
F    AssertionError: this is error
== #2: test.py:test_fail ============================================================================================================================================================================================
 - Additional Details:
    > Log: '/home/eli/sentinel-qa-results/6e7b0ae0-09cc-11e5-bd41-28d24459a522_0/6e7b0ae0-09cc-11e5-bd41-28d24459a522_0_2/debug.log.txt'
 - 1/1 F (2015-06-03 11:42:13 +03:00):   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 /home/eli/qa/test.py:7
 def test_fail():
>    slash.assert_true(False, "this is failure")
F    TestFailed: this is failure (False is not true)
============================================================== Session ended. 0 successful, 0 skipped, 2 failures, 0 errors. Total duration: 00:00:00 ===============================================================
```

```
$ cat testsuite.xml 
<testsuite errors="0" failures="2" hostname="eplautlt" name="slash-suite" skipped="0" tests="2" time="0" timestamp="2015-06-03T11:42:13"><testcase classname="FunctionTest" name="&lt;Runnable test &lt;test.py:test_error&gt;&gt;" time="0"><error message="this is error" type="AssertionError">Traceback (most recent call last):
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/runner.py", line 161, in _get_test_hooks_context
    yield
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/runner.py", line 111, in _get_run_context_stack
    yield True
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/runner.py", line 52, in run_tests
    test.run()
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/core/function_test.py", line 23, in run
    is_method=False
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/core/fixtures/fixture_store.py", line 36, in call_with_fixtures
    return test_func(**kwargs)
  File "/home/eli/qa/test.py", line 4, in test_error
    assert False, "this is error"
AssertionError: this is error
</error></testcase><testcase classname="FunctionTest" name="&lt;Runnable test &lt;test.py:test_fail&gt;&gt;" time="0"><failure message="this is failure (False is not true)" type="TestFailed">Traceback (most recent call last):
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/runner.py", line 161, in _get_test_hooks_context
    yield
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/runner.py", line 111, in _get_run_context_stack
    yield True
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/runner.py", line 52, in run_tests
    test.run()
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/core/function_test.py", line 23, in run
    is_method=False
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/core/fixtures/fixture_store.py", line 36, in call_with_fixtures
    return test_func(**kwargs)
  File "/home/eli/qa/test.py", line 7, in test_fail
    slash.assert_true(False, "this is failure")
  File "/home/eli/qa/.venv/local/lib/python2.7/site-packages/slash/assertions.py", line 31, in _assertion
    raise TestFailed(msg)
TestFailed: this is failure (False is not true)
</failure></testcase></testsuite>(.venv) 
```

**Comment by vmalloc** [comment]
I fixed this on `develop` - please test and make sure this works for you now. The next version is bound to be release at the end of June.
